### ISSUE TITLE
No suitable driver for ... - Oracle driver is not loaded

### ISSUE THREAD

**Issue by jgarec** [utPLSQL/utPLSQL-maven-plugin#11]
Hi, 

As discussed in #9, i need to explicitly load oracle driver class. If not, the plugin won't work :
"no suitable driver for ..".

What do you think about creating a new optional parameter : 
```
    @Parameter(defaultValue = "oracle.jdbc.OracleDriver")
    private String driverClass;
```

and then check / load the driver (class.forname will initialize the class (registering the driver in a static method)
```
// Load driver
Class.forName(driverClass); 
```

Is there any case where users have to use another driver class ?

Or we could use the same code used in the cli : 
https://github.com/utPLSQL/utPLSQL-cli/blob/develop/src/main/java/org/utplsql/cli/OracleLibraryChecker.java

**Comment by pesse** [comment]
Don't think there is any need for flexibility of driver class in maven-plugin. You wouldn't embed that into other solutions but instead use java-api. Therefore no need for more complexity.

**Comment by alberto-hernandez** [comment]
I can't reproduce the problem.

**Comment by jgarec** [comment]
Yeah that’s strange.
It’s not necessary when i run the « unit test project ».
But i need to add this line when using the plugin with a real project.

**Comment by alberto-hernandez** [comment]
The oracle driver is a transitive dependency from the api that use the maven-plugin, so this is very strange.
Could you provide more information about your environment (JDK, SO)

**Comment by jgarec** [comment]
Can't reproduce anymore ....
