### ISSUE TITLE
adds support for regex, owner, type, name parameters

### ISSUE THREAD

**Issue by jgarec** [utPLSQL/utPLSQL-maven-plugin#12]
Hi,

Seems pretty easy to add support of those parameters.
Before submitting a new PR, are you ok with adding : 
```
	@Parameter
	private String srcRegexExpression;
	
	@Parameter
	private Integer srcOwnerSubexpression;
	
	@Parameter
	private Integer srcNameSubexpression;
	
	@Parameter
	private Integer srcTypeSubexpression;
```

and then 
```
	FileMapperOptions sourceMappingOptions = buildOptions(sources, PluginDefault.buildDefaultSource(), "sources");
	sourceMappingOptions.setRegexPattern(srcRegexExpression);
	sourceMappingOptions.setOwnerSubExpression(srcOwnerSubexpression);
	sourceMappingOptions.setNameSubExpression(srcNameSubexpression);
	sourceMappingOptions.setTypeSubExpression(srcTypeSubexpression);
```

Same with testRegexExpression, testOwnerSubexpression, testNameSubexpression, testTypeSubexpression

**Comment by alberto-hernandez** [comment]
Implemented but not tested. It seems pretty straight forward to pass this parameters.

**Comment by alberto-hernandez** [comment]
I will sumit a second test with full feature.

About the testTypeSubexpression, If the plugin has no value to provide to the API they should let the API to take its default value. Now, currently is the same (null) but in the future it will break the compatibility if we don't check it.

I will appreciate if you provide documentation of this parameter in the Readme.
