### ISSUE TITLE
Review all parameter names

### ISSUE THREAD

**Issue by jgarec** [utPLSQL/utPLSQL-maven-plugin#17]
In #16, @jgebal asks if "path" parameters should be renamed to something like suitepaths.

I think we should check that all parameters have almost the same names as in the CLI.

**Comment by jgarec** [comment]
hi @jgebal, here is a comparaison of all parameters :

You asked in #16 if path should be renamed to something like suite_paths. But i think paths.path is consistent with the CLI.

| CLI short parameter | CLI long parameter | maven XML path |
| --- | --- | --- |
| -c | --color | |
| | --failure-exit-code | |
| | | ignoreFailure |
| -f | --format | reporters.reporter.name |
| -o | | reporters.reporter.fileOutput |
| -s | | reporters.reporter.consoleOutput |
| -p | --path | paths.path |
| -scc | --skip-compatibility-check | skipCompatibilityCheck |
| -exclude | | excludeObject |
| -include | | includeObject |
| | | |
| -source_path | | sources.source.directory |
| -owner | | _not yet implemented_ |
| -regex_expression | | sourcesRegexExpression |
| -type_mapping | | _not yet implemented_ |
| -owner_subexpression | | sourcesOwnerSubexpression |
| -type_subexpression | | sourcesTypeSubexpression |
| -name_subexpression | | sourcesNameSubexpression |
| | | |
| -test_path | | tests.test.directory |
| -regex_expression | | testsRegexExpression |
| -type_mapping | | _not yet implemented_ |
| -owner_subexpression | | testsOwnerSubexpression |
| -type_subexpression | | testsTypeSubexpression |
| -name_subexpression | | testsNameSubexpression |

**Comment by jgebal** [comment]
This is a great mapping. 
Maybe we should add this to the project's readme?
It would be a shame to loose it.

**Comment by pesse** [comment]
I totally agree: great mapping, awesome work.

**Comment by jgarec** [comment]
Sure, let's see with @alberto-hernandez if all parameters are ok or if we need to modify some of them.
Then we need to add missing parameters (if necessary).

**Comment by jgarec** [comment]
Added in #18

**Comment by jgebal** [comment]
Closing as #18 is merged
