### ISSUE TITLE
<color>true/false</color> should be supported

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#27]
The documentation reporter comes with option to display results in color.
It would be good to have that option available in maven plugin

**Comment by jgarec** [comment]
The activation of color flag seems to be based on a system property, not on a flag in pom.xml

https://github.com/utPLSQL/utPLSQL-maven-plugin/blob/b13cd2a56396d8d3c44427c6f9b58acf8db0bcd8/utplsql-maven-plugin/src/main/java/org/utplsql/maven/plugin/helper/PluginDefault.java#L73-L80

**Comment by jgebal** [comment]
That's fine.
Then the trouble is on my local env as I get color output from maven but reporter output is without color.
Probably relovling of color doesn't always work properly.

**Comment by jgarec** [comment]
if i force the value, it gives that :

<img width="1331" alt="capture d ecran 2018-07-30 a 20 28 41" src="https://user-images.githubusercontent.com/16031094/43415932-36a7b0ca-9437-11e8-9d29-1f31b6ba5814.png">

just need to fix the way we activate (or not) the color.

**Comment by jgebal** [comment]
Do you get color without forcing it on your machine?

**Comment by jgarec** [comment]
In this version, you have to set an environment variable before running the plugin : 
export style.color=always

I don't like this solution.
All parameters should be taken from pom.xml or defined with default values if not provided. They shouldn't be taken from system/env properties because i think it adds too much complexity.

**Comment by jgebal** [comment]
Maven somehow "knows" if it should provide output in color. Maybe we can just check if maven is displaying in color or not.

**Comment by jgarec** [comment]
You're right, we can ask maven if coloration is activated or not.
