### ISSUE TITLE
Console output behavior

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#29]
When configuring reporters like below:
```
                    <reporters>
                        <reporter>
                            <name>UT_DOCUMENTATION_REPORTER</name>
                        </reporter>
                        <reporter>
                            <name>UT_COVERAGE_SONAR_REPORTER</name>
                            <fileOutput>coverage-sonar-reporter.xml</fileOutput>
                        </reporter>
                        <reporter>
                            <name>UT_SONAR_TEST_REPORTER</name>
                            <fileOutput>utplsql/sonar-test-reporter.xml</fileOutput>
                            <consoleOutput>true</consoleOutput>
                        </reporter>
                    </reporters>
```
The behavior should be:
- UT_DOCUMENTATION_REPORTER has <consoleOutput>true</consoleOutput>, since <fileOutput>is not specified
- UT_COVERAGE_SONAR_REPORTER has <consoleOutput>false</consoleOutput>, since <fileOutput>is specified 
- UT_SONAR_TEST_REPORTER respects the explicit setting of <consoleOutput>

The current behavior is not correct for situation when neither <consoleOutput> nor <fileOutput>is specified. In such case, <consoleOutput>should be defaulted to TRUE.

In case when <fileOutput> is specified, <consoleOutput> should default to FALSE.

**Comment by jgarec** [comment]
So it only concerns UT_DOCUMENTATION_REPORTER ? By default consoleOutput should be true. 
For others, by default, consoleOutput is false. Right ?

**Comment by jgebal** [comment]
Not exactly.
If no fileOutput specified -> default true
If fileOutput specified -> default false
If explicitly provided->accept what is provided
