### ISSUE TITLE
Add support for random order (3.1.7 feature)

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#42]
There are 2 new parameters coming in utPLSQL 3.1.7
It would be great to have them supported by cli
utPLSQL/utPLSQL#422
utPLSQL/utPLSQL#878

**Comment by viniciusam** [comment]
I've pushed a snapshot version with the changes:
<groupId>org.utplsql</groupId>
<artifactId>utplsql-maven-plugin</artifactId>
<version>3.1.3-20200225.224438-25</version>

I will create the official release later this week.
