### ISSUE TITLE
Invalid schema error 

### ISSUE THREAD

**Issue by preethileela** [utPLSQL/utPLSQL-maven-plugin#47]
The test case execution passed still during report generation for code coverage system is throwing invalid schema for package schema name.ut_runner.
The package is in valid state.
For testing When I run ut.run(testpackage) it run fine whereas when I run ut.run(actualpackage) in database it's throwing invalid schema ut_runner.Is that mean instead of testpackage actualpackage is passed as input during pom report execution.Not sure which Param I am wrong

**Comment by jgebal** [comment]
utPLSQL v3 doesn't keep any correlation between test package and actual package.

You need to provide test package name or test schema name to run the test package or all test packages in test schema.

You may also provide test suite path as parameter value.

It is described in utPLSQL documentation.

**Comment by preethileela** [comment]
Yea added test schema name and works fine

**Comment by preethileela** [comment]
Still objectes are failed in compilation actual source and test file path as src/main/resources and src/test/resources . It's copying the files to target directory but no objects to compile message is thrown and build is sucess. When coverage reporter runs it is not covering any lines.

**Comment by jgebal** [comment]
Did you go through our coverage guide in utPLSQL documentation?
It explains different options and directory configurations.
You need ro provide valid project files mapping for utPLSQL to be able to generate file-based coverage reports

**Comment by preethileela** [comment]
Yes it's working good now.

**Comment by preethileela** [comment]
The XML is generated is ther any configuration in pom which sends the report to sonar server
