### ISSUE TITLE
Sonar is unable to read .PRC and other extensions

### ISSUE THREAD

**Issue by preethileela** [utPLSQL/utPLSQL-maven-plugin#49]
Sonar qube is unable to recognize the provided format in utplsql such as .PRC.,.trg etc.
Please advice

**Comment by pesse** [comment]
Hi @preethileela,
does this existing issue help?
https://github.com/utPLSQL/utPLSQL/issues/941

If not, can you describe your actual problem in more detail, share what you tried already?

**Comment by preethileela** [comment]
Added sonar.plsql.file.prefixes=.PRC
That solves my issue
