### ISSUE TITLE
Add support for file mapping options

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#5]
As in cli, maven plugin needs to provide options to define how files will be mapped to DB objects

**Comment by jgarec** [comment]
#15 adds support for regex parameters.

If i compare with the CLI, only this parameter is now missing :
 -type_mapping="matched_string=TYPE[/matched_string=TYPE]*"

**Comment by jgarec** [comment]
All parameters are available with #18 and #16.
