### ISSUE TITLE
Add support for tags (3.1.7 feature)

### ISSUE THREAD

**Issue by michalpravda** [utPLSQL/utPLSQL-maven-plugin#50]
I would like to be able to declare tags of tests I [don't] want to run.

Semantically the same ability as:
select * from table(ut.run(a_tags => 'api,fast,-complex'));

Probably like:
`<configuration><tests><test><tags>api,fast,-complex</tags></test></tests></configuration>`

**Comment by pesse** [comment]
I agree that this would be awesome - unfortunately we don't have an active maintainer for the Maven plugin at the moment.
It shouldn't be too complicated to add the functionality because it is already implemented in the java-api.
Maybe you want to get engaged yourself with open source? :)

**Comment by michalpravda** [comment]
I'll try, but knowing little about Java and nothing about Maven it will
take a while.


st 12. 2. 2020 v 10:50 odesílatel Samuel Nitsche <notifications@github.com>
napsal:

**Comment by viniciusam** [comment]
Hi, I already started the work for this feature on branch release/3.1.3. I want to add one more feature, but I hope to release it this week.

**Comment by viniciusam** [comment]
I've pushed a snapshot version with the changes:
<groupId>org.utplsql</groupId>
<artifactId>utplsql-maven-plugin</artifactId>
<version>3.1.3-20200225.224438-25</version>

I will create the official release later this week.

**Comment by michalpravda** [comment]
Thank you.
MP
