### ISSUE TITLE
Custom mapping query

### ISSUE THREAD

**Issue by preethileela** [utPLSQL/utPLSQL-maven-plugin#52]
Hi,
I was trying to use.sql file format for code coverage for which I am using object type mapping format in pom.xml.how can I append functions and procedures over here . I tried to add in custom mapping it doesn't work.pls help

<sourcesRegexExpression>.*/(\w+)/(\w+)/(\w+)\.\w{3}</sourcesRegexExpression>
                            <sourcesOwnerSubexpression>1</sourcesOwnerSubexpression>
                            <sourcesNameSubexpression>3</sourcesNameSubexpression>
                            <sourcesTypeSubexpression>2</sourcesTypeSubexpression>
                            <sourcesCustomTypeMapping>
                                <customTypeMapping>
                                    <type>package body</type>
                                    <customMapping>package_bodies</customMapping>
                                </customTypeMapping>
                            </sourcesCustomTypeMapping>

**Comment by jgebal** [comment]
Did yoy follow our guide on file mapping?
It cam be found [here](https://github.com/utPLSQL/utPLSQL/blob/develop/docs/userguide/coverage.md#project-based-coverage)

Hopefully examples provided there will help.

**Comment by preethileela** [comment]
Yes I have already gone through guide. I am looking for change in pom.xml. 
With the current sample pom.xml provided for object type mapping shows custom mapping for packages alone . When I add additional custom mapping for procedure only the latest object type mapping is considered.
Can you plz share ppm.xml with object type mapping for package,procedures,function.

**Comment by jgebal** [comment]
To be honest I didn't use this feature of maven-plugin as I always could rely on default mapping used by utPLSQL.

If you need to use custom mapping, I assume this should work:
```xml
<sourcesCustomTypeMapping>
    <customTypeMapping>
        <type>package body</type>
        <customMapping>pkb</customMapping>
    </customTypeMapping>
    <customTypeMapping>
        <type>type body</type>
        <customMapping>typ</customMapping>
    </customTypeMapping>
    <customTypeMapping>
        <type>trigger</type>
        <customMapping>tri</customMapping>
    </customTypeMapping>
    <customTypeMapping>
        <type>function</type>
        <customMapping>fun</customMapping>
    </customTypeMapping>
    <customTypeMapping>
        <type>procedure</type>
        <customMapping>pro</customMapping>
    </customTypeMapping>
</sourcesCustomTypeMapping>
```

If that doesn't help, can you share what have you tried and exactly what is your config?
In particular: folder structure, file naming conventions (name/extension) and pom configuration for running utPLSQL.

Thanks
Jacek

**Comment by jgebal** [comment]
@preethileela - Did you get your issue resolved?

**Comment by preethileela** [comment]
No @jgebal .
My project files all are in .SQL .but your example shows deafault mapping of.prc,.reg
Can u give sample for .SQL file for package body, function,procedurea

**Comment by preethileela** [comment]
It's working now I changed to my folder specification and it looks good

**Comment by jgebal** [comment]
@preethileela 
If you think it could help others that struggle wirh similar issues, you could open a PR to extend our documentation for file mapping.

We use markdown as documentation so it's pretty easy to grasp.

We welcome any helpful contributions.
