### ISSUE TITLE
When 3.1.3 release version will be made available to  all consumers

### ISSUE THREAD

**Issue by getshravan** [utPLSQL/utPLSQL-maven-plugin#54]
I am facing the same issue specified [here](https://github.com/utPLSQL/utPLSQL-maven-plugin/issues/23) and it got [fixed](https://github.com/utPLSQL/utPLSQL-maven-plugin/pull/44) in 3.1.3-SNAPSHOT, when can we expect to see 3.1.3 released version.

**Comment by jgebal** [comment]
Released today :)

**Comment by viniciusam** [comment]
@getshravan FYI, the new version is 3.1.4, might take a few hours to show up on
https://mvnrepository.com/artifact/org.utplsql/utplsql-maven-plugin

**Comment by getshravan** [comment]
@jgebal @viniciusam awesome, thanks for quick response.
