### ISSUE TITLE
Oracle depedency

### ISSUE THREAD

**Issue by dmuz** [utPLSQL/utPLSQL-maven-plugin#56]
Hi,

Please change oracle depedencies to group
com.oracle.database.jdbc

Same version, published by Oracle, but PUBLIC - no login to Oracle required;)

**Comment by jgebal** [comment]
@viniciusam @pesse 
Is this dependency in maven plugin or in cli?
If it is easy to fix we could release next version with just that fix in it.

**Comment by viniciusam** [comment]
My understanding is that the public group is "com.oracle.ojdbc" which is the one we're using on version 3.1.4, is this not the case?
https://medium.com/oracledevs/oracle-jdbc-drivers-on-maven-central-64fcf724d8b

**Comment by dmuz** [comment]
Deps from com.oracle.ojdbc are public, but need license aproovment (oracle account / login)

Look at this:
https://mvnrepository.com/artifact/com.oracle.database.nls/orai18n
https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8

**Comment by viniciusam** [comment]
@jgebal if I make this change in the plugin it will probably work fine, but we should do it in the Java API too to avoid any compatibility issues:
https://github.com/utPLSQL/utPLSQL-java-api/blob/develop/build.gradle.kts#L42

**Comment by pesse** [comment]
You folks are right. I'll change dependency in java-api.
I checked and the only thing I did when the licensing changed was to ship the JARs together with CLI, but didn't change the dependencies.
Will try to do that change and create a new java-api version quickly

**Comment by pesse** [comment]
For reference - here's the announcement of Oracle about them changing group IDs and putting their drivers to maven central: https://medium.com/oracledevs/all-in-and-new-groupids-oracle-jdbc-drivers-on-maven-central-a76d545954c6
Completely missed that - it was unfortunately not the case back when I did the cli shipping change in October.

**Comment by pesse** [comment]
I need to correct myself (too tired or diverted right now) once more.
This is the latest announcement of Kuassi Mensah about the change of group-ids from Feb 2020: https://medium.com/oracledevs/all-in-and-new-groupids-oracle-jdbc-drivers-on-maven-central-a76d545954c6
@viniciusam linked an earlier announcement of September 2019 where the group-id change was *not* announced.

**Comment by simasch** [comment]
Obsolete
