### ISSUE TITLE
MojoExecutionException - during Jenkins pipeline execution

### ISSUE THREAD

**Issue by mariuszpriv** [utPLSQL/utPLSQL-maven-plugin#57]
The declarative pipeline during unit test execution throwing exception:
[ERROR] Unexpected error opening file ouput 
org.apache.maven.plugin.MojoExecutionException: Unexpected error opening file ouput 
	at org.utplsql.maven.plugin.reporter.ReporterWriter.writeReports(ReporterWriter.java:101)
	at org.utplsql.maven.plugin.reporter.ReporterWriter.writeReporters(ReporterWriter.java:63)
	at org.utplsql.maven.plugin.UtPLSQLMojo.execute(UtPLSQLMojo.java:196)

This happen randomly every 2-4 executions.
Plugin version: 
<version>3.1.4</version>

**Comment by simasch** [comment]
@mariuszpriv Does this still happen?

**Comment by mariuszpriv** [comment]
Hi, I’m unable to confirm this, don’t have that env anymore.

Thanks,
Mariusz

**Comment by simasch** [comment]
Thanks @mariuszpriv for letting me know.
In that case I'm going to close the issue.
Please reopen or open a new issue whenever the problem should re-occur.
