### ISSUE TITLE
UTPLSQL As a JAVA API Usage- Request for Documentation

### ISSUE THREAD

**Issue by venkat-kasula** [utPLSQL/utPLSQL-maven-plugin#60]
Hi All, 

Is there any possiblity of using the UTPLSQL as a API Package which it can triggered using Java Program to execute it as part of my other Test Cases (UI/API related) when we integrate it using selenium. 

If there any is any documentation related to UTPLSQL API & their usage (which can be hosted independently ) could be useful.

**Comment by simasch** [comment]
You can use the Java API https://github.com/utPLSQL/utPLSQL-java-api
