### ISSUE TITLE
excludeObject and includeObject doesn't work for multiple values

### ISSUE THREAD

**Issue by Gepar** [utPLSQL/utPLSQL-maven-plugin#62]
According to documentation we can do this:
`<excludeObject>app.test1,app.test2</excludeObject>`
But according to maven plugin sources we can pass only one parameter because string is passing without split by any delimiter
```
                if (isNotBlank(excludeObject)) {
                    runner.excludeObject(excludeObject);
                }
```

**Comment by simasch** [comment]
Thank you for reporting the issue @Gepar 

I'll create a bugfix release in the next few days

**Comment by simasch** [comment]
Also includeObject has the same issue

**Comment by diamond54321** [comment]
@simasch, it seams there is a bug in your commit:
```
if (isNotBlank(includeObject)) {
                    if (includeObject.contains(",")) {
                        String[] includes = includeObject.split(",");
                        runner.excludeObjects(Arrays.asList(includes));
                    } else {
                        runner.excludeObject(includeObject);
                    }
                }
```
includeObject goes to runner.excludeObject now

**Comment by simasch** [comment]
Hi @diamond54321 Thanks a lot for the your bug report.
I'll go ahead and fix this asap

**Comment by simasch** [comment]
Added a new issue for this: #64

**Comment by simasch** [comment]
@diamond54321 a new release 3.1.9 with the fix has been released

**Comment by diamond54321** [comment]
@simasch thanks a lot for the rapid fix
