### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by Gepar** [utPLSQL/utPLSQL-maven-plugin#63]
Some params in documentation (readme.md) is wrong and migrated from older version, please fix it.

Only numbers here was expected:
`
<sourcesOwnerSubexpression>app</sourcesOwnerSubexpression>
<testsOwnerSubexpression>test</testsOwnerSubexpression>
`

And little misspell in comments:
`
        
        
        <dbPass>password</dbPass>
`
-DdbPass was expected.

**Comment by simasch** [comment]
Thanks for reporting. Will be fixed in the next release.
