### ISSUE TITLE
Tests runs only when dbUser = sourcesOwner

### ISSUE THREAD

**Issue by Gepar** [utPLSQL/utPLSQL-maven-plugin#68]
Find some strange bug: i've got empty reports when I run tests from any user != sourcesOwner.
For example I have user "debt" with package api and package test_api.
And I have user "some_user":

> create user some_user identified by "Qwerty12345";
> grant connect to some_user;
> grant execute any procedure to some_user;
> grant select any table to some_user;
> grant select any dictionary to some_user;

When i pass dbUser=debt - all reports are correct (coverage 100%), when I change dbUser=some_user - all reports are empty (coverage 0%).

My current configuration:

>         <configuration>
>           <sources>
>             <source>
>               <directory>src/main</directory>
>               <includes>
>                 <include>**/*pkb.sql</include>
>                 <include>**/*pks.sql</include>
>               </includes>
>             </source>
>           </sources>
>           <tests>
>             <test>
>               <directory>src/test</directory>
>               <includes>
>                 <include>**/*pkb.sql</include>
>                 <include>**/*pks.sql</include>
>               </includes>
>             </test>
>           </tests>
>           <sourcesRegexExpression>.*/\w+/(\w+)/(\w+)\.\w{3}\.\w{3}</sourcesRegexExpression>
>           <sourcesOwner>debt</sourcesOwner>
>           <sourcesTypeSubexpression>1</sourcesTypeSubexpression>
>           <sourcesNameSubexpression>2</sourcesNameSubexpression>
> 
>           <randomTestOrder>true</randomTestOrder>
>           <randomTestOrderSeed>5</randomTestOrderSeed>
>           <reporters>
>             <reporter>
>               <name>UT_COVERAGE_SONAR_REPORTER</name>
>               <fileOutput>coverage-sonar-report.xml</fileOutput>
>               <consoleOutput>false</consoleOutput>
>             </reporter>
>             <reporter>
>               <name>UT_COVERAGE_HTML_REPORTER</name>
>               <fileOutput>coverage-report.html</fileOutput>
>               <consoleOutput>false</consoleOutput>
>             </reporter>
>             <reporter>
>               <name>UT_SONAR_TEST_REPORTER</name>
>               <fileOutput>sonar-test-report.xml</fileOutput>
>               <consoleOutput>false</consoleOutput>
>             </reporter>
>           </reporters>
>         </configuration>

Also when i try to catch all queries on oracle when i run tests i found this:
> select /*+ cardinality(i 1) */ UT3.ut_annotation_obj_cache_info(
>     object_owner  => o.owner,
>     object_name   => o.object_name,
>     object_type   => o.object_type,
>     needs_refresh => 'Y',
>     parse_time    => c.parse_time         )
>     from dba_objects o
>     left join table( cast(:l_cached_objects as UT3.ut_annotation_objs_cache_info
>  ) ) c on o.owner       = c.object_owner
>   and o.object_name = c.object_name and o.object_type = c.object_type where o.owner       = 'SOME_USER'

And i can't find in trace files any mentions of sourcesOwner user, only dbUser.

**Comment by simasch** [comment]
Hi,
This is not a bug.
If the user is not the owner of the tests you must set the path:







<paths>
   <path>schema_name</path>
</paths>

**Comment by Gepar** [comment]
You right, it works and it was in docs!  Sorry, I don't know how I read docs last time and why i thought that param sourcesOwner is what I should change.
