### ISSUE TITLE
Releasing and publishing the plugin

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-maven-plugin#7]
We need to be able to release and publish the plugin so it can be discovered when added as dependency

**Comment by jgarec** [comment]
Should be published on packagecloud like java-api ?

**Comment by jgebal** [comment]
Whatever would work as a maven dependency.
We already have packagecloud account but maybe it's better to publish it via maven repository?
@pesse - any ideas?

**Comment by jgebal** [comment]
https://maven.apache.org/repository/guide-central-repository-upload.html

@viniciusam 
If you need help with any information that is need for publishing - let me know.
